import { TrailNode } from '../types';

export const MOCK_TRAILS: TrailNode[] = [
  {
    id: '1',
    title: 'Feminicídio',
    slug: 'feminicidio',
    status: 'unlocked', // Primeira trilha disponível
    colorClass: 'bg-red-500 text-white border-red-600',
    accentColorClass: 'bg-red-50 text-red-700',
    glowClass: 'animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-40',
    icon: 'Scale',
  },
  {
    id: '2',
    title: 'Bullying',
    slug: 'bullying',
    status: 'locked',
    colorClass: 'bg-amber-500 text-white border-amber-600 opacity-60',
    accentColorClass: 'bg-amber-50 text-amber-700',
    glowClass: '',
    icon: 'AlertTriangle',
  },
  {
    id: '3',
    title: 'Abuso Sexual',
    slug: 'abuso-sexual',
    status: 'locked',
    colorClass: 'bg-orange-500 text-white border-orange-600 opacity-60',
    accentColorClass: 'bg-orange-50 text-orange-700',
    glowClass: '',
    icon: 'ShieldAlert',
  },
  {
    id: '4',
    title: 'Direitos',
    slug: 'direitos',
    status: 'locked',
    colorClass: 'bg-sky-500 text-white border-sky-600 opacity-60',
    accentColorClass: 'bg-sky-50 text-sky-700',
    glowClass: '',
    icon: 'BookOpen',
  },
  {
    id: '5',
    title: 'Racismo',
    slug: 'racismo',
    status: 'locked',
    colorClass: 'bg-slate-600 text-white border-slate-700 opacity-60',
    accentColorClass: 'bg-slate-50 text-slate-700',
    glowClass: '',
    icon: 'Users',
  },
  {
    id: '6',
    title: 'Causa Animal',
    slug: 'causa-animal',
    status: 'locked',
    colorClass: 'bg-amber-800 text-white border-amber-900 opacity-60',
    accentColorClass: 'bg-amber-50 text-amber-900',
    glowClass: '',
    icon: 'Heart',
  },
];