/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f3fde9",
        "on-surface": "#151e12",
        "on-surface-variant": "#3d4b37",
        "surface-container": "#e7f1dd",
        "surface-container-low": "#edf7e3",
        "surface-container-high": "#e1ebd8",
        "surface-container-highest": "#dce6d2",
        "surface-variant": "#dce6d2",
        outline: "#6d7b65",
        "outline-variant": "#bccbb2",
        primary: "#136e00",
        "on-primary": "#ffffff",
        "primary-container": "#2bcc00",
        "on-primary-container": "#0b4f00",
        secondary: "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dddddd",
        tertiary: "#9c3c66",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ff8dba",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f3fde9",
        "feminicide-red": "#FF4B4B",
        "rights-blue": "#1CB0F6",
        "racism-gray": "#4B4B4B",
        "bullying-yellow": "#FFC800",
        "abuse-orange": "#FF9600",
        "animal-brown": "#A56032",
        "success-green": "#58CC02",
        "locked-gray": "#AFAFAF",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};
